import os
import datetime
import textwrap


def save_document(response_text: str, directory: str = "./output", filename: str = None):
    """Export travel plan to Markdown file with proper formatting."""
    os.makedirs(directory, exist_ok=True)

    # Create markdown content with metadata header
    markdown_content = textwrap.dedent(f"""\
    # 🌍 AI Travel Plan

    # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
    # **Created by:** Travel Agent

    ---

    {response_text}

    ---

    *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
    """)

    try:
        # Generate timestamp-based filename if not provided
        if not filename:
            timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
            filename = f"AI_Trip_Planner_{timestamp}.md"
        filepath = os.path.join(directory, filename)

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(markdown_content)

        print(f"Markdown file saved as: {filepath}")
        return filepath

    except Exception as e:
        print(f"Error saving markdown file: {e}")
        return None
